name: Unlock Test (windows)
on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */3 * * *'
jobs:
  batch_testing:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Testing Netflix Unlock Status
        env:
          GISTURL: ${{secrets.GISTURL}}
          SUBURL: ${{secrets.SUBURL}}
          TOKEN: ${{secrets.TOKEN}}
        run: |
          echo ($env:GISTURL) >> $env:GISTURL
          echo ($env:SUBURL) >> $env:SUBURL
          echo ($env:TOKEN) >> $env:TOKEN
          pip install -r requirements.txt
          python main.py -g $GISTURL -u $SUBURL -t $TOKEN
